### ISSUE TITLE
Color adjustment required for intellisense since VS Code 1.57

### ISSUE THREAD

**Issue by NKarolak** [martonsagi/nav-cside-color-theme#8]
It seems like VS Code version 1.57 introduced a new color scheme.
Using the default color scheme of VS Code, intellisense looks like that:
![image](https://user-images.githubusercontent.com/34504100/121689314-c1472c80-cac4-11eb-9a51-4a02a0ebd7ad.png)

When the Dynamics NAV C/Side Theme is active, it now looks like that:
![image](https://user-images.githubusercontent.com/34504100/121689405-da4fdd80-cac4-11eb-94d5-94a0346704ba.png)
The blue font and background color in the selected line are now too similar.

**Workaround:**
New user setting
```
"workbench.colorCustomizations": {
        "editorSuggestWidget.selectedBackground": "#adcde0"
    }
```
![image](https://user-images.githubusercontent.com/34504100/121690453-294a4280-cac6-11eb-96c9-90d007427c47.png)

**Comment by NKarolak** [comment]
Command palette with Dynamics NAV C/SIDE Theme active:
![image](https://user-images.githubusercontent.com/34504100/121849425-98ed4700-cceb-11eb-85a5-e7af30cf68f9.png)

Fixed with
```
  "workbench.colorCustomizations": {
        "quickInputList.focusBackground": "#adcde0"     
    }
```

**Comment by martonsagi** [comment]
Hi Natalie,

Thank you for the report, I changed the styling:

![image](https://user-images.githubusercontent.com/18100709/121850959-d6eb6a80-cced-11eb-9245-a604e48176f4.png)

**Comment by NKarolak** [comment]
Great, thank you - when will it be available? :-)

And would you fix also the other issues that I've created?

**Comment by martonsagi** [comment]
This update has just been published a couple minutes ago. :)
I can't make promises for the other issues in the near future due to lack of time :(

**Comment by NKarolak** [comment]
Version 0.0.8 installed and tested - thank you!
